KLIOSO SECURITY ALERT
=====================

🚨 {{ $alertType }}
Website: {{ $website->domain_name }}

ALERT DETAILS:
@if(isset($alertData['description']))
- Description: {{ $alertData['description'] }}
@endif
@if(isset($alertData['affected_files']))
- Affected Files: {{ implode(', ', $alertData['affected_files']) }}
@endif
@if(isset($alertData['recommendation']))
- Recommendation: {{ $alertData['recommendation'] }}
@endif
- Detected: {{ now()->format('Y-m-d H:i:s') }}
- Severity: {{ strtoupper($alertData['severity'] ?? 'MEDIUM') }}

WEBSITE INFORMATION:
- Domain: {{ $website->domain_name }}
- WordPress Version: {{ $website->wp_version ?? 'Unknown' }}
@if($website->hosting_provider)
- Hosting Provider: {{ $website->hosting_provider->name }}
@endif

View Details: {{ route('websites.show', $website->id) }}

---
This alert was generated by Klioso WordPress Management System
If you believe this is a false positive, please review your security settings.
