<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Security Alert - {{ $website->domain_name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background: linear-gradient(135deg, #dc3545 0%, #c82333 100%);
            color: white;
            padding: 30px;
            text-align: center;
            border-radius: 10px 10px 0 0;
        }
        .content {
            background: #f8f9fa;
            padding: 30px;
            border-radius: 0 0 10px 10px;
        }
        .alert-critical { border-left: 4px solid #dc3545; background: #f8d7da; }
        .alert-high { border-left: 4px solid #fd7e14; background: #fff3cd; }
        .alert-medium { border-left: 4px solid #ffc107; background: #fff3cd; }
        .alert-low { border-left: 4px solid #28a745; background: #d4edda; }
        .alert-box {
            padding: 20px;
            margin: 20px 0;
            border-radius: 8px;
        }
        .website-info {
            background: white;
            padding: 15px;
            border-radius: 6px;
            margin: 15px 0;
        }
        .button {
            display: inline-block;
            background: #dc3545;
            color: white;
            padding: 12px 30px;
            text-decoration: none;
            border-radius: 6px;
            margin: 15px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🚨 Security Alert</h1>
        <p>{{ $website->domain_name }}</p>
    </div>
    
    <div class="content">
        <div class="alert-box alert-{{ $alertData['severity'] ?? 'medium' }}">
            <h2>{{ $alertType }}</h2>
            <p><strong>Alert Details:</strong></p>
            <ul>
                @if(isset($alertData['description']))
                    <li>Description: {{ $alertData['description'] }}</li>
                @endif
                @if(isset($alertData['affected_files']))
                    <li>Affected Files: {{ implode(', ', $alertData['affected_files']) }}</li>
                @endif
                @if(isset($alertData['recommendation']))
                    <li>Recommendation: {{ $alertData['recommendation'] }}</li>
                @endif
                <li>Detected: {{ now()->format('Y-m-d H:i:s') }}</li>
                <li>Severity: {{ strtoupper($alertData['severity'] ?? 'MEDIUM') }}</li>
            </ul>
        </div>
        
        <div class="website-info">
            <h3>Website Information</h3>
            <p><strong>Domain:</strong> {{ $website->domain_name }}</p>
            <p><strong>WordPress Version:</strong> {{ $website->wp_version ?? 'Unknown' }}</p>
            @if($website->hosting_provider)
                <p><strong>Hosting Provider:</strong> {{ $website->hosting_provider->name }}</p>
            @endif
        </div>
        
        <a href="{{ route('websites.show', $website->id) }}" class="button">View Website Details</a>
        
        <div style="margin-top: 30px; text-align: center; color: #666; font-size: 14px;">
            <p>This alert was generated by Klioso WordPress Management System</p>
            <p>If you believe this is a false positive, please review your security settings.</p>
        </div>
    </div>
</body>
</html>
